Added do not work label
nanolos/nanolos-labelsync pull request #12
Opened 2021-06-07 20:00 UTC by cegan-wyer

### In This PR
Adds a new label "Do Not Work" that signifies if an issue/pr should not be worked on until explicit approval is given

Added at the request of the support/QA team

2021-06-20 23:53 UTC, joshjeppson requested changes

2021-06-20 23:53 UTC, joshjeppson commented on labelsync.yml
> +  # Plaid.NET-POC:
Let's remove this repo from the list.

2021-06-20 23:53 UTC, joshjeppson commented on labelsync.yml
> +  # PlaidTesting:
Let's remove this repo from the list.

2021-06-22 16:59 UTC, cegan-wyer commented on labelsync.yml
> +  # Plaid.NET-POC:
Done!

2021-06-22 18:59 UTC, joshjeppson approved these changes

2021-06-22 18:59 UTC, merged